using System.Globalization;

namespace MeowKey.Manager.Services;

public sealed class LocalizationService
{
    private static readonly Lazy<LocalizationService> CurrentInstance = new(() => new LocalizationService());

    private readonly IReadOnlyDictionary<string, string> _strings;

    public static LocalizationService Current => CurrentInstance.Value;

    public string LanguageTag { get; }

    public bool IsChinese => string.Equals(LanguageTag, "zh-CN", StringComparison.OrdinalIgnoreCase);

    private LocalizationService()
    {
        var cultureName = CultureInfo.CurrentUICulture.Name;
        if (cultureName.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
        {
            LanguageTag = "zh-CN";
            _strings = ZhCn;
            return;
        }

        if (cultureName.StartsWith("en", StringComparison.OrdinalIgnoreCase))
        {
            LanguageTag = "en-US";
            _strings = EnUs;
            return;
        }

        LanguageTag = "zh-CN";
        _strings = ZhCn;
    }

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        if (_strings.TryGetValue(key, out var localized))
        {
            return localized;
        }

        if (ZhCn.TryGetValue(key, out var fallback))
        {
            return fallback;
        }

        return key;
    }

    private static readonly IReadOnlyDictionary<string, string> ZhCn = new Dictionary<string, string>
    {
        ["App.WindowTitle"] = "MeowKey 管理器",
        ["App.ProductName"] = "MeowKey 管理器",
        ["App.WindowSubtitle"] = "正式管理器壳层",
        ["App.ChannelLabel"] = "管理器优先",
        ["App.WindowsLabel"] = "Windows",
        ["App.LinuxLabel"] = "Linux",
        ["App.WindowsSurface"] = "WinUI 3",
        ["App.LinuxSurface"] = "Rust + egui/eframe",

        ["Nav.Overview"] = "概览",
        ["Nav.Devices"] = "设备",
        ["Nav.Credentials"] = "凭据",
        ["Nav.Security"] = "安全",
        ["Nav.Maintenance"] = "维护",
        ["Nav.Activity"] = "关于",

        ["Section.Overview.Title"] = "概览",
        ["Section.Overview.Subtitle"] = "按 Android-Cam-Bridge 的节奏重组后的正式管理器桌面壳层。",
        ["Section.Devices.Title"] = "设备",
        ["Section.Devices.Subtitle"] = "用于盘点设备、确认角色和查看连接状态。",
        ["Section.Credentials.Title"] = "凭据",
        ["Section.Credentials.Subtitle"] = "用于查看凭据目录、申请短时授权并执行受控写操作。",
        ["Section.Security.Title"] = "安全",
        ["Section.Security.Subtitle"] = "把当前硬化边界、PIN 范围和 user presence 现实约束讲清楚。",
        ["Section.Maintenance.Title"] = "维护",
        ["Section.Maintenance.Subtitle"] = "驱动、诊断与支持动作集中在这里，不影响主操作路径。",
        ["Section.Activity.Title"] = "关于",
        ["Section.Activity.Subtitle"] = "显示应用版本、设备版本、USB 身份和底板信息。",

        ["Summary.PrimaryDevice.Label"] = "主设备",
        ["Summary.PrimaryDevice.Value"] = "MeowKey Hardened RP2350",
        ["Summary.PrimaryDevice.Detail"] = "面向正式发布设备和正式管理通道。",
        ["Summary.ReleaseMode.Label"] = "桌面定位",
        ["Summary.ReleaseMode.Value"] = "管理器优先",
        ["Summary.ReleaseMode.Detail"] = "术语和分区围绕管理动作组织，不再围绕原始协议测试。",
        ["Summary.CredentialFlow.Label"] = "凭据流程",
        ["Summary.CredentialFlow.Value"] = "权限 API 待补齐",
        ["Summary.CredentialFlow.Detail"] = "单条删除和结构化目录仍然需要正式管理通道。",
        ["Summary.LinuxUi.Label"] = "Linux UI",
        ["Summary.LinuxUi.Value"] = "Rust + egui",
        ["Summary.LinuxUi.Detail"] = "先复用现有跨平台后端，避免再引入第二套未成型桌面栈。",
        ["Summary.Device.Label"] = "设备",
        ["Summary.Firmware.Label"] = "固件",
        ["Summary.Credentials.Label"] = "凭据",
        ["Summary.Channel.Label"] = "通道",
        ["Summary.Channel.Ready"] = "正式管理通道已就绪",
        ["Summary.Device.Disconnected"] = "未连接设备",
        ["Summary.Value.Unknown"] = "未知",
        ["Summary.Value.Offline"] = "离线",

        ["Overview.Fact.Connection"] = "连接",
        ["Overview.Fact.Driver"] = "驱动",
        ["Overview.Fact.Board"] = "底板",
        ["Overview.Fact.Security"] = "安全姿态",
        ["Overview.Driver.WinUsb"] = "WinUSB 正式管理接口",
        ["Overview.Security.Signed"] = "Signed boot 已开启",
        ["Overview.Security.Unsigned"] = "Signed boot 未开启",

        ["Devices.Entry.Primary.Name"] = "主认证器",
        ["Devices.Entry.Primary.Role"] = "终端用户管理目标",
        ["Devices.Entry.Primary.Transport"] = "USB FIDO HID",
        ["Devices.Entry.Primary.State"] = "推荐",
        ["Devices.Entry.Primary.Detail"] = "这是管理器应该优先优化的发布基线设备形态，默认假设没有 Debug HID。",
        ["Devices.Entry.Bringup.Name"] = "联调构建",
        ["Devices.Entry.Bringup.Role"] = "开发恢复路径",
        ["Devices.Entry.Bringup.Transport"] = "USB FIDO HID + Debug HID",
        ["Devices.Entry.Bringup.State"] = "受限",
        ["Devices.Entry.Bringup.Detail"] = "它应该保留给维护和诊断，不该继续占据产品 UI 的中心。",
        ["Devices.Entry.Probe.Name"] = "Probe 固件",
        ["Devices.Entry.Probe.Role"] = "板卡识别流程",
        ["Devices.Entry.Probe.Transport"] = "USB 串口",
        ["Devices.Entry.Probe.State"] = "按需",
        ["Devices.Entry.Probe.Detail"] = "只在底板未知或需要生成新 preset 草案时进入 probe 路径。",
        ["Devices.Entry.None.Name"] = "未发现正式管理设备",
        ["Devices.Entry.None.Role"] = "等待 WinUSB 正式管理接口",
        ["Devices.Entry.None.Detail"] = "请先安装正式管理驱动，并连接带管理接口的新 PID 设备。",
        ["Devices.Item.FirmwareLabel"] = "固件",
        ["Devices.Item.BoardLabel"] = "底板",
        ["Devices.Item.TransportLabel"] = "传输",
        ["Devices.Role.Managed"] = "正式管理目标",
        ["Devices.Role.AuthOnly"] = "仅认证路径",
        ["Devices.State.DebugPresent"] = "带 Debug HID",
        ["Devices.State.ManagedOnly"] = "仅正式管理通道",
        ["Devices.Selection.Unavailable"] = "不可选择",
        ["Devices.Selection.Current"] = "当前设备",
        ["Devices.Selection.Switch"] = "切换到此设备",
        ["Devices.Policy1.Title"] = "默认发布基线",
        ["Devices.Policy1.Value"] = "硬化构建",
        ["Devices.Policy1.Detail"] = "管理器文案和动作都应默认假设普通用户场景下没有 Debug HID。",
        ["Devices.Policy2.Title"] = "板卡识别路径",
        ["Devices.Policy2.Value"] = "需要时走 probe",
        ["Devices.Policy2.Detail"] = "未知 RP2350 底板应该被路由到 probe 流程，而不是走零散的手动调试步骤。",
        ["Devices.Policy3.Title"] = "支持术语",
        ["Devices.Policy3.Value"] = "统一管理器语言",
        ["Devices.Policy3.Detail"] = "界面应使用设备、凭据、安全和维护术语，而不是继续沿用 CTAP 测试话术。",

        ["Credentials.Capability1.Name"] = "正式凭据目录",
        ["Credentials.Capability1.Status"] = "可通过正式管理通道读取",
        ["Credentials.Capability1.Detail"] = "正式管理通道现在已经能返回分页结构化目录，但仍然只开放只读摘要。",
        ["Credentials.Capability2.Name"] = "单条凭据删除",
        ["Credentials.Capability2.Status"] = "缺失",
        ["Credentials.Capability2.StatusReady"] = "正式通道可用",
        ["Credentials.Capability2.Detail"] = "如果没有这个能力，管理器就还不能像真正的 passkey 管理器那样工作。",
        ["Credentials.Capability3.Name"] = "受限写操作",
        ["Credentials.Capability3.Status"] = "缺失",
        ["Credentials.Capability3.StatusReady"] = "正式通道可用",
        ["Credentials.Capability3.Detail"] = "正式管理接口仍然没有带权限范围的写操作，危险动作也没有从 Debug HID 迁入。",
        ["Credentials.Capability4.Name"] = "清空全部凭据",
        ["Credentials.Capability4.Status"] = "可通过 Debug HID 获取",
        ["Credentials.Capability4.StatusLimited"] = "仅调试页可用",
        ["Credentials.Capability4.Detail"] = "这个能力应该归到维护区，而不是作为默认管理模式。",
        ["Credentials.Catalog.FactStatus"] = "目录状态",
        ["Credentials.Catalog.FactEntries"] = "已加载条目",
        ["Credentials.Catalog.FactStore"] = "存储格式",
        ["Credentials.Catalog.FactAuth"] = "管理授权",
        ["Credentials.Catalog.StatusUnavailable"] = "正式目录暂不可用",
        ["Credentials.Catalog.StatusReady"] = "正式目录已加载",
        ["Credentials.Catalog.StatusEmpty"] = "目录为空",
        ["Credentials.Catalog.DetailUnavailable"] = "当前设备可能仍停留在只支持基础快照的旧固件上。",
        ["Credentials.Catalog.DetailReady"] = "这些条目来自正式管理通道，不再依赖 Debug HID 摘要。",
        ["Credentials.Catalog.DetailEmpty"] = "正式管理通道可读，但当前没有已存储凭据。",
        ["Credentials.Catalog.AuthActive"] = "已授权",
        ["Credentials.Catalog.AuthInactive"] = "未授权",
        ["Credentials.Catalog.AuthActiveDetail"] = "剩余约 {0} 秒 · 权限掩码 0x{1:X}",
        ["Credentials.Catalog.AuthInactiveDetail"] = "需要设备本地确认后才能获取短时授权。",
        ["Credentials.Catalog.NoUser"] = "未命名用户",
        ["Credentials.Catalog.NoRp"] = "未提供 RP 预览",
        ["Credentials.Catalog.NoDisplay"] = "未提供显示名",
        ["Credentials.Catalog.Slot"] = "槽位",
        ["Credentials.Catalog.SignCount"] = "签名计数",
        ["Credentials.Catalog.Discoverable"] = "可发现",
        ["Credentials.Catalog.ServerSide"] = "非 discoverable",
        ["Credentials.Catalog.CredRandomReady"] = "credRandom 就绪",
        ["Credentials.Catalog.CredRandomMissing"] = "credRandom 缺失",
        ["Credentials.Catalog.IdPrefix"] = "ID 前缀",

        ["Security.Policy1.Title"] = "用户在场基线",
        ["Security.Policy1.Value"] = "BOOTSEL 双击",
        ["Security.Policy1.Detail"] = "当前默认流程对 bring-up 足够，但还缺更清晰的本地确认体验。",
        ["Security.Policy2.Title"] = "Client PIN 覆盖面",
        ["Security.Policy2.Value"] = "仅旧式 getPinToken",
        ["Security.Policy2.Detail"] = "权限范围 token 还没做完，所以管理器不能过度承诺安全的账户级管理动作。",
        ["Security.Policy3.Title"] = "Signed boot",
        ["Security.Policy3.Value"] = "可选开启",
        ["Security.Policy3.Detail"] = "Secure boot 和 anti-rollback 已有构建块，但仍然需要用户显式完成 provisioning。",
        ["Security.Policy4.Title"] = "调试暴露",
        ["Security.Policy4.Value"] = "默认关闭",
        ["Security.Policy4.Detail"] = "管理器应该偏向 hardened 构建，把 Debug HID 限定在维护和实验室流程里。",
        ["Security.Pin.Configured"] = "PIN 已配置",
        ["Security.Pin.NotConfigured"] = "PIN 未配置",
        ["Security.Pin.Retries"] = "剩余重试次数",
        ["Security.Policy3.ValueSigned"] = "Signed boot 已开启",
        ["Security.Policy3.ValueUnsigned"] = "Signed boot 未开启",
        ["Security.Policy3.DetailRollbackOn"] = "Anti-rollback 已开启",
        ["Security.Policy3.DetailRollbackOff"] = "Anti-rollback 未开启",
        ["Security.Policy4.ValueDebug"] = "Debug HID 可用",
        ["Security.Policy4.ValueManaged"] = "仅正式管理通道",
        ["Security.Policy4.DetailManaged"] = "桌面应用可在非 Debug HID 下读取正式管理通道。",
        ["Security.Policy4.DetailUnavailable"] = "当前没有可用的正式管理接口。",
        ["Security.Policy5.Title"] = "OTP bootFlags0",
        ["Security.Policy6.Title"] = "OTP bootFlags1",
        ["Security.Label.Effective"] = "生效配置",
        ["Security.Label.Persisted"] = "持久配置",
        ["Security.Label.OverrideOn"] = "会话覆盖已开启",
        ["Security.Label.OverrideOff"] = "会话覆盖未开启",
        ["Security.Label.Enabled"] = "启用状态",
        ["Security.Label.Source"] = "来源",
        ["Security.Label.TapCount"] = "按压次数",
        ["Security.Label.GestureWindow"] = "手势窗口",
        ["Security.Label.RequestTimeout"] = "请求超时",
        ["Security.Label.Gpio"] = "GPIO",
        ["Security.Label.Version"] = "版本",
        ["Security.Label.Management"] = "正式管理",
        ["Security.Label.FidoHid"] = "FIDO HID",
        ["Security.Label.CtapConfigured"] = "CTAP 已配置",
        ["Security.Label.SimulatedSecureElement"] = "模拟安全元件",
        ["Security.Label.RollbackRequired"] = "要求回滚保护",
        ["Security.Label.FlashBootDisabled"] = "禁用 Flash Boot",
        ["Security.Label.PicobootDisabled"] = "禁用 PicoBoot",
        ["Security.Label.KeyValidMask"] = "有效密钥掩码",
        ["Security.Label.KeyInvalidMask"] = "失效密钥掩码",
        ["Security.UserPresence.EffectiveUnavailable"] = "当前固件还没有暴露可分组展示的生效 UP 配置。",
        ["Security.UserPresence.PersistedUnavailable"] = "当前固件还没有暴露可分组展示的持久化 UP 配置。",
        ["Security.UserPresence.EffectiveOverrideDetail"] = "会话覆盖正在生效，当前需要以这组 effective 参数为准。",
        ["Security.UserPresence.EffectiveDetail"] = "这组参数代表当前真正参与 CTAP / 管理流程判定的 user presence 行为。",
        ["Security.UserPresence.PersistedOverrideDetail"] = "会话覆盖存在时，persisted 仍然是重启后会恢复的基线。",
        ["Security.UserPresence.PersistedDetail"] = "这组参数会被写入持久层，重启后仍会恢复。",
        ["Security.Value.Unavailable"] = "不可用",
        ["Security.Value.Enabled"] = "开启",
        ["Security.Value.Disabled"] = "关闭",
        ["Security.Value.ActiveLow"] = "低电平有效",
        ["Security.Value.ActiveHigh"] = "高电平有效",
        ["Security.Value.NotApplicable"] = "不适用",

        ["Maintenance.Command.Check.Label"] = "固件检查",
        ["Maintenance.Command.Check.Detail"] = "统一跑固件、probe、Rust 桌面壳层和 WinUI 桌面壳层检查。",
        ["Maintenance.Command.Build.Label"] = "默认构建",
        ["Maintenance.Command.Build.Detail"] = "离线友好的开发构建。",
        ["Maintenance.Command.Hardened.Label"] = "硬化构建",
        ["Maintenance.Command.Hardened.Detail"] = "不带 Debug HID 的发布基线。",
        ["Maintenance.Command.Probe.Label"] = "Probe 流程",
        ["Maintenance.Command.Probe.Detail"] = "为未知底板生成 preset 草案。",
        ["Debug.Command.InstallDriver.Label"] = "安装正式管理驱动",
        ["Debug.Command.InstallDriver.Detail"] = "把 `MI_01` 正式管理接口绑定到 WinUSB。",
        ["Debug.Command.RunManager.Label"] = "运行正式管理器",
        ["Debug.Command.RunManager.Detail"] = "启动 WinUI 3 管理器壳层并走正式管理通道。",
        ["Debug.Command.BuildDebug.Label"] = "构建 Debug 固件",
        ["Debug.Command.BuildDebug.Detail"] = "保留 Debug HID，用于高级调试页和实验室维护。",
        ["Debug.Command.Probe.Label"] = "运行 Probe",
        ["Debug.Command.Probe.Detail"] = "未知底板时走板卡识别链路。",

        ["Page.Dashboard.Title"] = "管理器总览",
        ["Page.Dashboard.Description1"] = "本页用于展示当前设备、固件和管理通道状态。",
        ["Page.Dashboard.Description2"] = "数据来自设备实时快照与正式管理接口。",
        ["Page.Dashboard.Action.RefreshDevice"] = "刷新设备信息",
        ["Page.Dashboard.Action.ViewDevices"] = "查看设备",
        ["Page.Dashboard.FactsTitle"] = "设备基础情况",
        ["Page.Dashboard.FactsDescription"] = "通过 WinUSB 管理通道读取设备基础信息与安全状态。",
        ["Page.Dashboard.BoundaryTitle"] = "发布策略",
        ["Page.Dashboard.BoundaryDescription"] = "发布版管理器遵循以下原则：",
        ["Page.Dashboard.NowLine1"] = "默认面向 hardened 设备和正式管理通道。",
        ["Page.Dashboard.NowLine2"] = "敏感写操作必须先申请授权并完成本地确认。",
        ["Page.Dashboard.NowLine3"] = "维护能力与日常管理能力保持分区展示。",

        ["Page.Devices.Title"] = "设备盘点",
        ["Page.Devices.Description"] = "用于查看设备角色、固件姿态、连接状态与底板信息。",
        ["Page.Devices.Action.Refresh"] = "刷新盘点",
        ["Page.Devices.Action.Probe"] = "安排 Probe",
        ["Page.Devices.PoliciesTitle"] = "设备策略",

        ["Page.Credentials.Title"] = "凭据管理",
        ["Page.Credentials.Description"] = "用于查看凭据目录、申请短时授权并执行受控删除。",
        ["Page.Credentials.Action.Refresh"] = "刷新目录",
        ["Page.Credentials.Action.RequestAuthorization"] = "申请授权",
        ["Page.Credentials.Action.PlanDelete"] = "规划单条删除",
        ["Page.Credentials.Action.DeleteBySlot"] = "按槽位删除",
        ["Page.Credentials.Action.Delete"] = "删除",
        ["Page.Credentials.Action.ViewDetails"] = "查看详情",
        ["Page.Credentials.Action.KeepSummary"] = "保留摘要路径",
        ["Page.Credentials.Authorize.FailedTitle"] = "申请授权失败",
        ["Page.Credentials.Authorize.FailedMessage"] = "设备未完成本地确认。点击“申请授权”后请在设备侧完成双击确认。",
        ["Page.Credentials.DeleteBySlot.Title"] = "按槽位删除凭据",
        ["Page.Credentials.DeleteBySlot.Placeholder"] = "输入槽位编号（例如 3）",
        ["Page.Credentials.DeleteBySlot.Invalid"] = "槽位编号格式不正确，请输入整数。",
        ["Page.Credentials.Delete.ConfirmTitle"] = "确认删除该凭据",
        ["Page.Credentials.Delete.ConfirmBody"] = "将删除槽位 {0} 的凭据：{1} / {2}。这个动作会直接写入设备。是否继续？",
        ["Page.Credentials.Delete.FailedTitle"] = "删除失败",
        ["Page.Credentials.Delete.FailedMessage"] = "设备拒绝了删除请求，请检查授权状态与设备连接。",
        ["Page.Credentials.Error.NoDevice"] = "当前没有可操作的正式管理设备。",
        ["Page.Credentials.CatalogTitle"] = "正式目录",
        ["Page.Credentials.CatalogDescription"] = "这个区块直接读取正式管理通道里的结构化凭据摘要，而不是继续展示调试转储。",
        ["Page.Credentials.Filter.Search"] = "搜索",
        ["Page.Credentials.Filter.Type"] = "类型过滤",
        ["Page.Credentials.Filter.Health"] = "状态过滤",
        ["Page.Credentials.Filter.Sort"] = "排序",
        ["Page.Credentials.Filter.SearchPlaceholder"] = "按 RP、用户名、显示名或 ID 前缀过滤",
        ["Page.Credentials.Filter.TypeAll"] = "全部类型",
        ["Page.Credentials.Filter.TypeDiscoverable"] = "仅 discoverable",
        ["Page.Credentials.Filter.TypeServerSide"] = "仅非 discoverable",
        ["Page.Credentials.Filter.HealthAll"] = "全部状态",
        ["Page.Credentials.Filter.HealthReady"] = "仅 credRandom 就绪",
        ["Page.Credentials.Filter.HealthMissing"] = "仅 credRandom 缺失",
        ["Page.Credentials.Filter.SortSlot"] = "按槽位",
        ["Page.Credentials.Filter.SortSignCount"] = "按签名计数",
        ["Page.Credentials.Filter.SortUser"] = "按用户",
        ["Page.Credentials.Filter.SortRp"] = "按 RP",
        ["Page.Credentials.AuthCountdown.NoDevice"] = "授权状态：当前无设备。",
        ["Page.Credentials.AuthCountdown.Inactive"] = "授权状态：未授权。",
        ["Page.Credentials.AuthCountdown.Active"] = "授权状态：剩余约 {0} 秒（权限 0x{1:X}）。",
        ["Page.Credentials.Guidance.NoDeviceTitle"] = "还没有选中的管理设备",
        ["Page.Credentials.Guidance.NoDeviceDescription"] = "多设备场景下，这个页面只消费当前选中设备。请先到设备页切换上下文。",
        ["Page.Credentials.Guidance.NoDeviceLine1"] = "打开“设备”页，明确切到目标设备后再查看目录。",
        ["Page.Credentials.Guidance.NoDeviceLine2"] = "不要把不同设备的凭据目录混成同一个摘要面板。",
        ["Page.Credentials.Guidance.NoDeviceLine3"] = "后续写操作也必须基于这个选中设备上下文执行。",
        ["Page.Credentials.Guidance.UnsupportedTitle"] = "当前固件还不支持正式凭据目录",
        ["Page.Credentials.Guidance.UnsupportedDescription"] = "已连接设备能返回基础快照，但还没有实现 0x03 正式凭据摘要分页，或仍停留在旧固件版本。",
        ["Page.Credentials.Guidance.UnsupportedLine1"] = "先确认目标设备已刷入带正式管理目录扩展的新固件。",
        ["Page.Credentials.Guidance.UnsupportedLine2"] = "如果你只是需要实验室清空 / 调试摘要，继续去维护页走 Debug HID。",
        ["Page.Credentials.Guidance.UnsupportedLine3"] = "终端用户路径不要再把旧调试摘要包装成正式目录。",
        ["Page.Credentials.Guidance.AuthorizationTitle"] = "凭据目录需要先申请授权",
        ["Page.Credentials.Guidance.AuthorizationDescription"] = "当前设备启用了摘要读授权门控。请先点击“申请授权”，然后在设备上完成本地在场确认。",
        ["Page.Credentials.Guidance.AuthorizationLine1"] = "点击“申请授权”后，设备会进入短时确认窗口。",
        ["Page.Credentials.Guidance.AuthorizationLine2"] = "在窗口内完成双击 UP，再点击“刷新目录”。",
        ["Page.Credentials.Guidance.AuthorizationLine3"] = "授权默认是短时 token，过期后需要重新申请。",
        ["Page.Credentials.EmptyCatalogTitle"] = "目录为空",
        ["Page.Credentials.EmptyCatalogDescription"] = "正式管理通道已经可读，但当前设备还没有已存储凭据。",
        ["Page.Credentials.NoMatchTitle"] = "没有匹配的目录项",
        ["Page.Credentials.NoMatchDescription"] = "当前筛选条件下没有符合条件的凭据，请放宽搜索或过滤器。",
        ["Page.Credentials.Detail.CredentialLength"] = "凭据 ID 长度",
        ["Page.Credentials.Detail.RpPreview"] = "RP 预览",
        ["Page.Credentials.Detail.UserPreview"] = "用户名预览",
        ["Page.Credentials.Detail.DisplayPreview"] = "显示名预览",
        ["Page.Credentials.Detail.Discoverable"] = "发现方式",
        ["Page.Credentials.Detail.CredRandom"] = "credRandom 状态",
        ["Page.Credentials.CapabilityTitle"] = "当前能力图",
        ["Page.Credentials.EmptyStateTitle"] = "空状态方向",
        ["Page.Credentials.EmptyStateDescription"] = "在协议真正具备正式管理面前，页面应该优先展示清晰的空状态，而不是伪造凭据条目。",
        ["Page.Credentials.EmptyStateNowTitle"] = "目录为空时的说明",
        ["Page.Credentials.EmptyStateLine1"] = "单条凭据动作被刻意按下，直到固件能安全授权这些操作。",
        ["Page.Credentials.EmptyStateLine2"] = "批量破坏性操作应该归到维护区，而不是首次使用体验。",
        ["Page.Credentials.EmptyStateLine3"] = "友好的账户标签和元数据需要结构化目录，而不是调试转储。",

        ["Page.Security.Title"] = "安全基线",
        ["Page.Security.Description"] = "展示当前固件安全姿态、用户在场策略与可用保护能力。",
        ["Page.Security.Action.Refresh"] = "刷新安全状态",
        ["Page.Security.Action.PromoteSecureReady"] = "强调 Secure-Ready",
        ["Page.Security.Action.KeepDebugLimited"] = "限制 Debug 暴露",
        ["Page.Security.Action.ApplyUpPersisted"] = "写入持久配置",
        ["Page.Security.Action.ApplyUpSession"] = "写入会话覆盖",
        ["Page.Security.Action.ClearUpSession"] = "清除会话覆盖",
        ["Page.Security.UserPresenceTitle"] = "User Presence 分组",
        ["Page.Security.UserPresenceDescription"] = "把 effective / persisted 分开看，避免会话覆盖和持久配置被压缩成一句摘要文本。",
        ["Page.Security.ManageUpTitle"] = "管理器写配置",
        ["Page.Security.ManageUpDescription"] = "通过正式管理通道直接写 user presence。写入前会走设备在场确认和短时授权。",
        ["Page.Security.UpField.Source"] = "来源",
        ["Page.Security.UpField.GpioPin"] = "GPIO 引脚",
        ["Page.Security.UpField.TapCount"] = "按压次数",
        ["Page.Security.UpField.GestureWindow"] = "手势窗口（ms）",
        ["Page.Security.UpField.RequestTimeout"] = "请求超时（ms）",
        ["Page.Security.UpField.ActiveLow"] = "GPIO 极性",
        ["Page.Security.UpField.ActiveLowCheckbox"] = "低电平有效",
        ["Page.Security.UpSource.None"] = "none",
        ["Page.Security.UpSource.Bootsel"] = "bootsel",
        ["Page.Security.UpSource.Gpio"] = "gpio",
        ["Page.Security.UpApply.InvalidTitle"] = "参数无效",
        ["Page.Security.UpApply.InvalidMessage"] = "请输入有效的 user presence 参数。",
        ["Page.Security.UpApply.InvalidGpio"] = "GPIO 引脚必须是整数。",
        ["Page.Security.UpApply.InvalidTap"] = "按压次数必须是整数。",
        ["Page.Security.UpApply.InvalidGesture"] = "手势窗口必须是整数毫秒。",
        ["Page.Security.UpApply.InvalidTimeout"] = "请求超时必须是整数毫秒。",
        ["Page.Security.UpApply.FailedTitle"] = "写入失败",
        ["Page.Security.UpApply.FailedMessage"] = "设备拒绝了配置写入，请检查在场确认与授权状态。",
        ["Page.Security.Error.NoDevice"] = "当前没有可操作的正式管理设备。",
        ["Page.Security.RecommendationTitle"] = "推荐的产品语气",
        ["Page.Security.RecommendationDescription"] = "以 hardened 构建、user presence 默认值和显式 provisioning 说明为主。把 Debug HID、破坏性凭据擦除和协议 bring-up 面板压缩到维护语境下。",

        ["Page.Maintenance.Title"] = "维护与支持",
        ["Page.Maintenance.Description"] = "这里提供驱动、诊断与支持动作。默认日常流程不依赖此页。",
        ["Page.Maintenance.Action.PrepareRelease"] = "刷新正式通道",
        ["Page.Maintenance.Action.ProbeReminder"] = "记录支持备注",
        ["Page.Maintenance.ToneTitle"] = "使用边界",
        ["Page.Maintenance.ToneDescription"] = "默认使用正式管理通道；维护动作仅在需要时执行。",
        ["Page.Maintenance.LogTitle"] = "操作记录",

        ["Page.Activity.Title"] = "关于",
        ["Page.Activity.Description"] = "显示应用版本、设备版本、USB 身份、序列号和底板摘要，便于发布与支持。",
        ["Page.Activity.Action.RecordSnapshot"] = "刷新设备信息",
        ["Page.Activity.Action.PinLinux"] = "记录关于信息",
        ["Page.Activity.DetailsTitle"] = "版本与设备信息",

        ["About.Item.AppVersion"] = "应用版本",
        ["About.Item.DeviceVersion"] = "设备固件版本",
        ["About.Item.DeviceName"] = "设备名称",
        ["About.Item.UsbIdentity"] = "USB 身份",
        ["About.Item.Board"] = "底板信息",

        ["Activity.Category.shell"] = "壳层",
        ["Activity.Category.platform"] = "平台",
        ["Activity.Category.cleanup"] = "清理",
        ["Activity.Category.debug"] = "调试",
        ["Activity.Category.overview"] = "概览",
        ["Activity.Category.devices"] = "设备",
        ["Activity.Category.credentials"] = "凭据",
        ["Activity.Category.security"] = "安全",
        ["Activity.Category.maintenance"] = "维护",
        ["Activity.Category.activity"] = "活动",

        ["Action.Overview.ViewDevices"] = "已从概览页切到设备页。",
        ["Action.Devices.Refresh"] = "已检查设备盘点卡片，确保壳层持续围绕管理角色组织。",
        ["Action.Devices.Probe"] = "已为下一块未知 RP2350 底板安排新的 probe-board 流程。",
        ["Action.Devices.Select"] = "已切换当前选中设备，后续凭据与安全页面会跟随这个上下文刷新。",
        ["Action.Credentials.RefreshCatalog"] = "已通过正式管理通道刷新凭据目录。",
        ["Action.Credentials.RequestAuthorization"] = "已向设备发送授权申请，等待本地在场确认。",
        ["Action.Credentials.Delete"] = "已通过正式管理通道执行单条凭据删除。",
        ["Action.Credentials.KeepSummary"] = "已将 Debug HID 摘要列表限定在维护语境中，而不是把它升级成普通管理视图。",
        ["Action.Security.RefreshState"] = "已通过正式管理通道刷新安全状态。",
        ["Action.Security.PromoteSecureReady"] = "已把 secure-boot-ready hardened 构建提升为优先审查目标。",
        ["Action.Security.KeepDebugLimited"] = "已明确把 Debug HID 限定在维护和实验室流程中。",
        ["Action.Security.ApplyUpPersisted"] = "已通过正式管理通道写入持久化 user presence 配置。",
        ["Action.Security.ApplyUpSession"] = "已通过正式管理通道写入会话态 user presence 覆盖。",
        ["Action.Security.ClearUpSession"] = "已清除会话态 user presence 覆盖。",
        ["Action.Maintenance.PrepareRelease"] = "已准备新的桌面预检路径：Rust 管理器检查加 WinUI 管理器构建。",
        ["Action.Maintenance.ProbeReminder"] = "已补充提醒：未知底板先走 probe-board，而不是直接散做调试步骤。",
        ["Action.Activity.RecordSnapshot"] = "已刷新正式管理通道上的设备信息。",
        ["Action.Activity.PinLinux"] = "已记录当前应用与设备版本信息。",
        ["Dialog.Close"] = "关闭"
    };

    private static readonly IReadOnlyDictionary<string, string> EnUs = new Dictionary<string, string>
    {
        ["App.WindowTitle"] = "MeowKey Manager",
        ["App.ProductName"] = "MeowKey Manager",
        ["App.WindowSubtitle"] = "Production Manager Shell",
        ["App.ChannelLabel"] = "Manager First",
        ["App.WindowsLabel"] = "Windows",
        ["App.LinuxLabel"] = "Linux",
        ["App.WindowsSurface"] = "WinUI 3",
        ["App.LinuxSurface"] = "Rust + egui/eframe",

        ["Nav.Overview"] = "Overview",
        ["Nav.Devices"] = "Devices",
        ["Nav.Credentials"] = "Credentials",
        ["Nav.Security"] = "Security",
        ["Nav.Maintenance"] = "Maintenance",
        ["Nav.Activity"] = "About",

        ["Section.Overview.Title"] = "Overview",
        ["Section.Overview.Subtitle"] = "A production-oriented desktop shell reorganized with the Android-Cam-Bridge layout rhythm.",
        ["Section.Devices.Title"] = "Devices",
        ["Section.Devices.Subtitle"] = "Used to inventory devices, confirm roles, and view connection status.",
        ["Section.Credentials.Title"] = "Credentials",
        ["Section.Credentials.Subtitle"] = "Used to browse the credential catalog, request short-lived authorization, and perform controlled writes.",
        ["Section.Security.Title"] = "Security",
        ["Section.Security.Subtitle"] = "Make current hardening boundaries, PIN scope, and user-presence constraints explicit.",
        ["Section.Maintenance.Title"] = "Maintenance",
        ["Section.Maintenance.Subtitle"] = "Keep drivers, diagnostics, and support actions here without affecting the primary path.",
        ["Section.Activity.Title"] = "About",
        ["Section.Activity.Subtitle"] = "Show app version, device version, USB identity, and board details.",

        ["Summary.PrimaryDevice.Label"] = "Primary Device",
        ["Summary.PrimaryDevice.Value"] = "MeowKey Hardened RP2350",
        ["Summary.PrimaryDevice.Detail"] = "Target release devices and the formal management channel.",
        ["Summary.ReleaseMode.Label"] = "Desktop Posture",
        ["Summary.ReleaseMode.Value"] = "Manager First",
        ["Summary.ReleaseMode.Detail"] = "Terminology and sections are organized around management actions instead of raw protocol tests.",
        ["Summary.CredentialFlow.Label"] = "Credential Flow",
        ["Summary.CredentialFlow.Value"] = "Scoped API Pending",
        ["Summary.CredentialFlow.Detail"] = "Single-delete and a structured catalog still require a formal management channel.",
        ["Summary.LinuxUi.Label"] = "Linux UI",
        ["Summary.LinuxUi.Value"] = "Rust + egui",
        ["Summary.LinuxUi.Detail"] = "Reuse the existing cross-platform backend before introducing a second unfinished desktop stack.",
        ["Summary.Device.Label"] = "Device",
        ["Summary.Firmware.Label"] = "Firmware",
        ["Summary.Credentials.Label"] = "Credentials",
        ["Summary.Channel.Label"] = "Channel",
        ["Summary.Channel.Ready"] = "Management channel ready",
        ["Summary.Device.Disconnected"] = "No device connected",
        ["Summary.Value.Unknown"] = "Unknown",
        ["Summary.Value.Offline"] = "Offline",

        ["Overview.Fact.Connection"] = "Connection",
        ["Overview.Fact.Driver"] = "Driver",
        ["Overview.Fact.Board"] = "Board",
        ["Overview.Fact.Security"] = "Security",
        ["Overview.Driver.WinUsb"] = "WinUSB management interface",
        ["Overview.Security.Signed"] = "Signed boot enabled",
        ["Overview.Security.Unsigned"] = "Signed boot disabled",

        ["Devices.Entry.Primary.Name"] = "Primary Token",
        ["Devices.Entry.Primary.Role"] = "End-user management target",
        ["Devices.Entry.Primary.Transport"] = "USB FIDO HID",
        ["Devices.Entry.Primary.State"] = "Preferred",
        ["Devices.Entry.Primary.Detail"] = "This is the baseline device shape the manager should optimize for when Debug HID is absent.",
        ["Devices.Entry.Bringup.Name"] = "Bring-up Build",
        ["Devices.Entry.Bringup.Role"] = "Developer recovery path",
        ["Devices.Entry.Bringup.Transport"] = "USB FIDO HID + Debug HID",
        ["Devices.Entry.Bringup.State"] = "Limited",
        ["Devices.Entry.Bringup.Detail"] = "Keep it available for maintenance and diagnostics, but do not let it dominate the product UI.",
        ["Devices.Entry.Probe.Name"] = "Probe Firmware",
        ["Devices.Entry.Probe.Role"] = "Board discovery workflow",
        ["Devices.Entry.Probe.Transport"] = "USB serial",
        ["Devices.Entry.Probe.State"] = "Conditional",
        ["Devices.Entry.Probe.Detail"] = "Use probe only when the board identity is unknown or when a new preset draft is required.",
        ["Devices.Entry.None.Name"] = "No managed device found",
        ["Devices.Entry.None.Role"] = "Waiting for the WinUSB management interface",
        ["Devices.Entry.None.Detail"] = "Install the management driver first and connect a device that exposes the new manager PID.",
        ["Devices.Item.FirmwareLabel"] = "Firmware",
        ["Devices.Item.BoardLabel"] = "Board",
        ["Devices.Item.TransportLabel"] = "Transport",
        ["Devices.Role.Managed"] = "Managed device",
        ["Devices.Role.AuthOnly"] = "Authentication only",
        ["Devices.State.DebugPresent"] = "Debug HID present",
        ["Devices.State.ManagedOnly"] = "Management channel only",
        ["Devices.Selection.Unavailable"] = "Unavailable",
        ["Devices.Selection.Current"] = "Current device",
        ["Devices.Selection.Switch"] = "Switch to this device",
        ["Devices.Policy1.Title"] = "Default shipping baseline",
        ["Devices.Policy1.Value"] = "Hardened build",
        ["Devices.Policy1.Detail"] = "Manager copy and actions should assume Debug HID is absent in normal end-user usage.",
        ["Devices.Policy2.Title"] = "Board discovery path",
        ["Devices.Policy2.Value"] = "Probe when needed",
        ["Devices.Policy2.Detail"] = "Unknown RP2350 boards should be routed through probe instead of ad-hoc manual debug steps.",
        ["Devices.Policy3.Title"] = "Support tone",
        ["Devices.Policy3.Value"] = "Manager terms only",
        ["Devices.Policy3.Detail"] = "Use device, credential, security, and maintenance language instead of raw CTAP testing vocabulary.",

        ["Credentials.Capability1.Name"] = "Formal credential catalog",
        ["Credentials.Capability1.Status"] = "Readable through the formal management channel",
        ["Credentials.Capability1.Detail"] = "The formal management channel now returns a paged structured catalog, but it is still read-only.",
        ["Credentials.Capability2.Name"] = "Single credential delete",
        ["Credentials.Capability2.Status"] = "Missing",
        ["Credentials.Capability2.StatusReady"] = "Available on management channel",
        ["Credentials.Capability2.Detail"] = "Without this, the app still cannot behave like a real passkey manager.",
        ["Credentials.Capability3.Name"] = "Scoped write actions",
        ["Credentials.Capability3.Status"] = "Missing",
        ["Credentials.Capability3.StatusReady"] = "Available on management channel",
        ["Credentials.Capability3.Detail"] = "The formal management interface still has no permission-scoped writes, and dangerous actions have not moved over from Debug HID.",
        ["Credentials.Capability4.Name"] = "Clear all credentials",
        ["Credentials.Capability4.Status"] = "Available through Debug HID",
        ["Credentials.Capability4.StatusLimited"] = "Debug page only",
        ["Credentials.Capability4.Detail"] = "Keep this in maintenance instead of presenting it as the default management path.",
        ["Credentials.Catalog.FactStatus"] = "Catalog status",
        ["Credentials.Catalog.FactEntries"] = "Loaded entries",
        ["Credentials.Catalog.FactStore"] = "Store format",
        ["Credentials.Catalog.FactAuth"] = "Manager authorization",
        ["Credentials.Catalog.StatusUnavailable"] = "Formal catalog unavailable",
        ["Credentials.Catalog.StatusReady"] = "Formal catalog loaded",
        ["Credentials.Catalog.StatusEmpty"] = "Catalog empty",
        ["Credentials.Catalog.DetailUnavailable"] = "This device may still be on older firmware that only supports the baseline snapshot.",
        ["Credentials.Catalog.DetailReady"] = "These rows come from the formal management channel instead of a Debug HID summary dump.",
        ["Credentials.Catalog.DetailEmpty"] = "The formal management channel is readable, but there are no stored credentials right now.",
        ["Credentials.Catalog.AuthActive"] = "Authorized",
        ["Credentials.Catalog.AuthInactive"] = "Not authorized",
        ["Credentials.Catalog.AuthActiveDetail"] = "About {0}s remaining · permission mask 0x{1:X}",
        ["Credentials.Catalog.AuthInactiveDetail"] = "A short-lived authorization requires local confirmation on the device.",
        ["Credentials.Catalog.NoUser"] = "Unnamed user",
        ["Credentials.Catalog.NoRp"] = "No RP preview",
        ["Credentials.Catalog.NoDisplay"] = "No display name",
        ["Credentials.Catalog.Slot"] = "Slot",
        ["Credentials.Catalog.SignCount"] = "Sign count",
        ["Credentials.Catalog.Discoverable"] = "Discoverable",
        ["Credentials.Catalog.ServerSide"] = "Non-discoverable",
        ["Credentials.Catalog.CredRandomReady"] = "credRandom ready",
        ["Credentials.Catalog.CredRandomMissing"] = "credRandom missing",
        ["Credentials.Catalog.IdPrefix"] = "ID prefix",

        ["Security.Policy1.Title"] = "User-presence baseline",
        ["Security.Policy1.Value"] = "BOOTSEL double tap",
        ["Security.Policy1.Detail"] = "The current default is enough for bring-up, but it still needs a clearer local confirmation story.",
        ["Security.Policy2.Title"] = "Client PIN coverage",
        ["Security.Policy2.Value"] = "Legacy getPinToken only",
        ["Security.Policy2.Detail"] = "Permission-scoped tokens are unfinished, so the manager must not over-promise safe account-level admin actions.",
        ["Security.Policy3.Title"] = "Signed boot",
        ["Security.Policy3.Value"] = "Opt-in",
        ["Security.Policy3.Detail"] = "Secure boot and anti-rollback are present as building blocks, but they still require explicit user-driven provisioning.",
        ["Security.Policy4.Title"] = "Debug exposure",
        ["Security.Policy4.Value"] = "Keep off by default",
        ["Security.Policy4.Detail"] = "The manager should bias toward hardened builds and relegate Debug HID to maintenance and lab workflows.",
        ["Security.Pin.Configured"] = "PIN configured",
        ["Security.Pin.NotConfigured"] = "PIN not configured",
        ["Security.Pin.Retries"] = "Remaining retries",
        ["Security.Policy3.ValueSigned"] = "Signed boot enabled",
        ["Security.Policy3.ValueUnsigned"] = "Signed boot disabled",
        ["Security.Policy3.DetailRollbackOn"] = "Anti-rollback enabled",
        ["Security.Policy3.DetailRollbackOff"] = "Anti-rollback disabled",
        ["Security.Policy4.ValueDebug"] = "Debug HID available",
        ["Security.Policy4.ValueManaged"] = "Management channel only",
        ["Security.Policy4.DetailManaged"] = "The desktop app can read the formal management channel without Debug HID.",
        ["Security.Policy4.DetailUnavailable"] = "No formal management interface is currently available.",
        ["Security.Policy5.Title"] = "OTP bootFlags0",
        ["Security.Policy6.Title"] = "OTP bootFlags1",
        ["Security.Label.Effective"] = "Effective",
        ["Security.Label.Persisted"] = "Persisted",
        ["Security.Label.OverrideOn"] = "Session override on",
        ["Security.Label.OverrideOff"] = "Session override off",
        ["Security.Label.Enabled"] = "Enabled",
        ["Security.Label.Source"] = "Source",
        ["Security.Label.TapCount"] = "Tap count",
        ["Security.Label.GestureWindow"] = "Gesture window",
        ["Security.Label.RequestTimeout"] = "Request timeout",
        ["Security.Label.Gpio"] = "GPIO",
        ["Security.Label.Version"] = "Version",
        ["Security.Label.Management"] = "Management",
        ["Security.Label.FidoHid"] = "FIDO HID",
        ["Security.Label.CtapConfigured"] = "CTAP configured",
        ["Security.Label.SimulatedSecureElement"] = "Simulated secure element",
        ["Security.Label.RollbackRequired"] = "Rollback required",
        ["Security.Label.FlashBootDisabled"] = "Flash boot disabled",
        ["Security.Label.PicobootDisabled"] = "Picoboot disabled",
        ["Security.Label.KeyValidMask"] = "Key-valid mask",
        ["Security.Label.KeyInvalidMask"] = "Key-invalid mask",
        ["Security.UserPresence.EffectiveUnavailable"] = "This firmware does not expose a grouped effective UP view yet.",
        ["Security.UserPresence.PersistedUnavailable"] = "This firmware does not expose a grouped persisted UP view yet.",
        ["Security.UserPresence.EffectiveOverrideDetail"] = "A session override is active, so these effective values are the ones currently driving user-presence checks.",
        ["Security.UserPresence.EffectiveDetail"] = "These are the values currently enforced by CTAP and the management surface.",
        ["Security.UserPresence.PersistedOverrideDetail"] = "Even when a session override is active, persisted values remain the reboot baseline.",
        ["Security.UserPresence.PersistedDetail"] = "These values are stored durably and come back after reboot.",
        ["Security.Value.Unavailable"] = "Unavailable",
        ["Security.Value.Enabled"] = "Enabled",
        ["Security.Value.Disabled"] = "Disabled",
        ["Security.Value.ActiveLow"] = "Active low",
        ["Security.Value.ActiveHigh"] = "Active high",
        ["Security.Value.NotApplicable"] = "Not applicable",

        ["Maintenance.Command.Check.Label"] = "Firmware check",
        ["Maintenance.Command.Check.Detail"] = "Run firmware, probe, Rust desktop, and WinUI desktop checks together.",
        ["Maintenance.Command.Build.Label"] = "Default build",
        ["Maintenance.Command.Build.Detail"] = "Offline-friendly developer build.",
        ["Maintenance.Command.Hardened.Label"] = "Hardened build",
        ["Maintenance.Command.Hardened.Detail"] = "Release-like baseline without Debug HID.",
        ["Maintenance.Command.Probe.Label"] = "Probe workflow",
        ["Maintenance.Command.Probe.Detail"] = "Generate preset drafts for unknown boards.",
        ["Debug.Command.InstallDriver.Label"] = "Install management driver",
        ["Debug.Command.InstallDriver.Detail"] = "Bind the `MI_01` management interface to WinUSB.",
        ["Debug.Command.RunManager.Label"] = "Run manager shell",
        ["Debug.Command.RunManager.Detail"] = "Launch the WinUI 3 manager shell on the formal management channel.",
        ["Debug.Command.BuildDebug.Label"] = "Build debug firmware",
        ["Debug.Command.BuildDebug.Detail"] = "Keep Debug HID enabled for the advanced debug page and lab workflows.",
        ["Debug.Command.Probe.Label"] = "Run probe",
        ["Debug.Command.Probe.Detail"] = "Use the board-discovery path for unknown hardware.",

        ["Page.Dashboard.Title"] = "Manager Overview",
        ["Page.Dashboard.Description1"] = "This page summarizes current device, firmware, and management-channel status.",
        ["Page.Dashboard.Description2"] = "All data is sourced from live device snapshots and the formal management interface.",
        ["Page.Dashboard.Action.RefreshDevice"] = "Refresh Device Info",
        ["Page.Dashboard.Action.ViewDevices"] = "View Devices",
        ["Page.Dashboard.FactsTitle"] = "Device Basics",
        ["Page.Dashboard.FactsDescription"] = "Reads device basics and posture through the formal WinUSB management channel.",
        ["Page.Dashboard.BoundaryTitle"] = "Release Policy",
        ["Page.Dashboard.BoundaryDescription"] = "The release manager follows these principles:",
        ["Page.Dashboard.NowLine1"] = "Default to hardened devices and the formal management channel.",
        ["Page.Dashboard.NowLine2"] = "Sensitive writes require authorization plus local confirmation.",
        ["Page.Dashboard.NowLine3"] = "Maintenance features stay separated from daily operations.",

        ["Page.Devices.Title"] = "Device Inventory",
        ["Page.Devices.Description"] = "View device roles, firmware posture, connectivity, and board identity.",
        ["Page.Devices.Action.Refresh"] = "Refresh Inventory",
        ["Page.Devices.Action.Probe"] = "Queue Probe Pass",
        ["Page.Devices.PoliciesTitle"] = "Device Policies",

        ["Page.Credentials.Title"] = "Credential Management",
        ["Page.Credentials.Description"] = "Browse the credential catalog, request short-lived authorization, and perform controlled deletion.",
        ["Page.Credentials.Action.Refresh"] = "Refresh Catalog",
        ["Page.Credentials.Action.RequestAuthorization"] = "Request Authorization",
        ["Page.Credentials.Action.PlanDelete"] = "Plan Single Delete",
        ["Page.Credentials.Action.DeleteBySlot"] = "Delete by Slot",
        ["Page.Credentials.Action.Delete"] = "Delete",
        ["Page.Credentials.Action.ViewDetails"] = "View Details",
        ["Page.Credentials.Action.KeepSummary"] = "Keep Summary Path",
        ["Page.Credentials.Authorize.FailedTitle"] = "Authorization Request Failed",
        ["Page.Credentials.Authorize.FailedMessage"] = "The device did not complete local confirmation. Click \"Request Authorization\" and finish the double-press on the device.",
        ["Page.Credentials.DeleteBySlot.Title"] = "Delete Credential by Slot",
        ["Page.Credentials.DeleteBySlot.Placeholder"] = "Enter slot index (for example: 3)",
        ["Page.Credentials.DeleteBySlot.Invalid"] = "Slot index is invalid. Please enter an integer.",
        ["Page.Credentials.Delete.ConfirmTitle"] = "Delete this credential?",
        ["Page.Credentials.Delete.ConfirmBody"] = "This will delete slot {0}: {1} / {2}. The change is written directly to the device. Continue?",
        ["Page.Credentials.Delete.FailedTitle"] = "Delete failed",
        ["Page.Credentials.Delete.FailedMessage"] = "The device rejected the delete request. Check authorization and connection state.",
        ["Page.Credentials.Error.NoDevice"] = "No managed device is currently available for this action.",
        ["Page.Credentials.CatalogTitle"] = "Formal Catalog",
        ["Page.Credentials.CatalogDescription"] = "This section reads structured credential summaries directly from the formal management channel instead of showing a debug dump.",
        ["Page.Credentials.Filter.Search"] = "Search",
        ["Page.Credentials.Filter.Type"] = "Type",
        ["Page.Credentials.Filter.Health"] = "Health",
        ["Page.Credentials.Filter.Sort"] = "Sort",
        ["Page.Credentials.Filter.SearchPlaceholder"] = "Filter by RP, username, display name, or ID prefix",
        ["Page.Credentials.Filter.TypeAll"] = "All types",
        ["Page.Credentials.Filter.TypeDiscoverable"] = "Discoverable only",
        ["Page.Credentials.Filter.TypeServerSide"] = "Non-discoverable only",
        ["Page.Credentials.Filter.HealthAll"] = "All states",
        ["Page.Credentials.Filter.HealthReady"] = "credRandom ready only",
        ["Page.Credentials.Filter.HealthMissing"] = "credRandom missing only",
        ["Page.Credentials.Filter.SortSlot"] = "Sort by slot",
        ["Page.Credentials.Filter.SortSignCount"] = "Sort by sign count",
        ["Page.Credentials.Filter.SortUser"] = "Sort by user",
        ["Page.Credentials.Filter.SortRp"] = "Sort by RP",
        ["Page.Credentials.AuthCountdown.NoDevice"] = "Authorization: no device selected.",
        ["Page.Credentials.AuthCountdown.Inactive"] = "Authorization: inactive.",
        ["Page.Credentials.AuthCountdown.Active"] = "Authorization: about {0}s remaining (permissions 0x{1:X}).",
        ["Page.Credentials.Guidance.NoDeviceTitle"] = "No managed device is currently selected",
        ["Page.Credentials.Guidance.NoDeviceDescription"] = "This page only consumes the current device context in a multi-device setup. Switch devices first.",
        ["Page.Credentials.Guidance.NoDeviceLine1"] = "Open the Devices page and make the target device current before reviewing its catalog.",
        ["Page.Credentials.Guidance.NoDeviceLine2"] = "Do not merge multiple devices into one credential summary surface.",
        ["Page.Credentials.Guidance.NoDeviceLine3"] = "Future write actions must also anchor themselves to this selected-device context.",
        ["Page.Credentials.Guidance.UnsupportedTitle"] = "This firmware does not support the formal credential catalog yet",
        ["Page.Credentials.Guidance.UnsupportedDescription"] = "The device can still return the baseline snapshot, but it does not implement the paged 0x03 credential summaries yet or it is still on older firmware.",
        ["Page.Credentials.Guidance.UnsupportedLine1"] = "Flash a firmware build that includes the formal credential-catalog extension first.",
        ["Page.Credentials.Guidance.UnsupportedLine2"] = "If you only need lab-only wipe or debug summaries, keep using Debug HID in maintenance.",
        ["Page.Credentials.Guidance.UnsupportedLine3"] = "Do not present legacy debug summaries as if they were a real end-user catalog.",
        ["Page.Credentials.Guidance.AuthorizationTitle"] = "Credential catalog requires authorization first",
        ["Page.Credentials.Guidance.AuthorizationDescription"] = "This device enforces authorization gating for summary reads. Click \"Request Authorization\" and complete local confirmation on the device.",
        ["Page.Credentials.Guidance.AuthorizationLine1"] = "After you request authorization, the device opens a short confirmation window.",
        ["Page.Credentials.Guidance.AuthorizationLine2"] = "Complete the UP double-press within that window, then click \"Refresh Catalog\".",
        ["Page.Credentials.Guidance.AuthorizationLine3"] = "The token is short-lived and must be requested again after it expires.",
        ["Page.Credentials.EmptyCatalogTitle"] = "Catalog is empty",
        ["Page.Credentials.EmptyCatalogDescription"] = "The formal management channel is readable, but this device does not currently store any credentials.",
        ["Page.Credentials.NoMatchTitle"] = "No catalog entries match",
        ["Page.Credentials.NoMatchDescription"] = "Nothing matches the current search and filter combination. Broaden the query and try again.",
        ["Page.Credentials.Detail.CredentialLength"] = "Credential ID length",
        ["Page.Credentials.Detail.RpPreview"] = "RP preview",
        ["Page.Credentials.Detail.UserPreview"] = "Username preview",
        ["Page.Credentials.Detail.DisplayPreview"] = "Display-name preview",
        ["Page.Credentials.Detail.Discoverable"] = "Discovery mode",
        ["Page.Credentials.Detail.CredRandom"] = "credRandom state",
        ["Page.Credentials.CapabilityTitle"] = "Current Capability Map",
        ["Page.Credentials.EmptyStateTitle"] = "Empty-State Direction",
        ["Page.Credentials.EmptyStateDescription"] = "Until the protocol grows a proper management surface, the page should prefer a clear empty state over fake credential rows.",
        ["Page.Credentials.EmptyStateNowTitle"] = "When the catalog is empty",
        ["Page.Credentials.EmptyStateLine1"] = "Per-credential actions are intentionally held back until the firmware can authorize them safely.",
        ["Page.Credentials.EmptyStateLine2"] = "Bulk destructive actions belong in maintenance, not in the first-run experience.",
        ["Page.Credentials.EmptyStateLine3"] = "Friendly account labels and metadata require a structured catalog, not a debug dump.",

        ["Page.Security.Title"] = "Security Baseline",
        ["Page.Security.Description"] = "Show current firmware security posture, user-presence policy, and available protections.",
        ["Page.Security.Action.Refresh"] = "Refresh Security State",
        ["Page.Security.Action.PromoteSecureReady"] = "Promote Secure-Ready",
        ["Page.Security.Action.KeepDebugLimited"] = "Keep Debug Limited",
        ["Page.Security.Action.ApplyUpPersisted"] = "Write Persisted Config",
        ["Page.Security.Action.ApplyUpSession"] = "Write Session Override",
        ["Page.Security.Action.ClearUpSession"] = "Clear Session Override",
        ["Page.Security.UserPresenceTitle"] = "Grouped User Presence",
        ["Page.Security.UserPresenceDescription"] = "Keep effective and persisted UP separate so session overrides do not collapse into one line of card text.",
        ["Page.Security.ManageUpTitle"] = "Managed UP Writes",
        ["Page.Security.ManageUpDescription"] = "Write user-presence settings over the formal management channel. The device enforces local confirmation and short-lived authorization.",
        ["Page.Security.UpField.Source"] = "Source",
        ["Page.Security.UpField.GpioPin"] = "GPIO Pin",
        ["Page.Security.UpField.TapCount"] = "Tap Count",
        ["Page.Security.UpField.GestureWindow"] = "Gesture Window (ms)",
        ["Page.Security.UpField.RequestTimeout"] = "Request Timeout (ms)",
        ["Page.Security.UpField.ActiveLow"] = "GPIO Polarity",
        ["Page.Security.UpField.ActiveLowCheckbox"] = "Active low",
        ["Page.Security.UpSource.None"] = "none",
        ["Page.Security.UpSource.Bootsel"] = "bootsel",
        ["Page.Security.UpSource.Gpio"] = "gpio",
        ["Page.Security.UpApply.InvalidTitle"] = "Invalid input",
        ["Page.Security.UpApply.InvalidMessage"] = "Please enter valid user-presence parameters.",
        ["Page.Security.UpApply.InvalidGpio"] = "GPIO pin must be an integer.",
        ["Page.Security.UpApply.InvalidTap"] = "Tap count must be an integer.",
        ["Page.Security.UpApply.InvalidGesture"] = "Gesture window must be an integer in milliseconds.",
        ["Page.Security.UpApply.InvalidTimeout"] = "Request timeout must be an integer in milliseconds.",
        ["Page.Security.UpApply.FailedTitle"] = "Write failed",
        ["Page.Security.UpApply.FailedMessage"] = "The device rejected the configuration write. Check local confirmation and authorization state.",
        ["Page.Security.Error.NoDevice"] = "No managed device is currently available for this action.",
        ["Page.Security.RecommendationTitle"] = "Recommended Product Tone",
        ["Page.Security.RecommendationDescription"] = "Lead with hardened builds, user-presence defaults, and explicit provisioning notes. Keep Debug HID, destructive credential wipes, and protocol bring-up panels inside maintenance language.",

        ["Page.Maintenance.Title"] = "Maintenance and Support",
        ["Page.Maintenance.Description"] = "This page provides driver, diagnostics, and support actions. Daily workflows should not depend on it.",
        ["Page.Maintenance.Action.PrepareRelease"] = "Refresh management channel",
        ["Page.Maintenance.Action.ProbeReminder"] = "Log support note",
        ["Page.Maintenance.ToneTitle"] = "Usage Boundary",
        ["Page.Maintenance.ToneDescription"] = "Default to the formal management channel and use maintenance actions only when required.",
        ["Page.Maintenance.LogTitle"] = "Operation Log",

        ["Page.Activity.Title"] = "About",
        ["Page.Activity.Description"] = "Show app version, device version, USB identity, serial, and board summary for release and support workflows.",
        ["Page.Activity.Action.RecordSnapshot"] = "Refresh device info",
        ["Page.Activity.Action.PinLinux"] = "Log about info",
        ["Page.Activity.DetailsTitle"] = "Version and Device Details",

        ["About.Item.AppVersion"] = "App version",
        ["About.Item.DeviceVersion"] = "Device firmware version",
        ["About.Item.DeviceName"] = "Device name",
        ["About.Item.UsbIdentity"] = "USB identity",
        ["About.Item.Board"] = "Board",

        ["Activity.Category.shell"] = "Shell",
        ["Activity.Category.platform"] = "Platform",
        ["Activity.Category.cleanup"] = "Cleanup",
        ["Activity.Category.debug"] = "Debug",
        ["Activity.Category.overview"] = "Overview",
        ["Activity.Category.devices"] = "Devices",
        ["Activity.Category.credentials"] = "Credentials",
        ["Activity.Category.security"] = "Security",
        ["Activity.Category.maintenance"] = "Maintenance",
        ["Activity.Category.activity"] = "Activity",

        ["Action.Overview.ViewDevices"] = "Switched from overview to the devices page.",
        ["Action.Devices.Refresh"] = "Reviewed device inventory cards to keep the shell centered on management roles.",
        ["Action.Devices.Probe"] = "Queued a fresh probe-board pass for the next unknown RP2350 board.",
        ["Action.Devices.Select"] = "Switched the current device context so credentials and security views now follow that selection.",
        ["Action.Credentials.RefreshCatalog"] = "Refreshed the credential catalog through the formal management channel.",
        ["Action.Credentials.RequestAuthorization"] = "Sent an authorization request to the device and waiting for local confirmation.",
        ["Action.Credentials.Delete"] = "Deleted one credential through the formal management channel.",
        ["Action.Credentials.KeepSummary"] = "Kept Debug HID summary listing scoped to maintenance instead of promoting it into a normal manager view.",
        ["Action.Security.RefreshState"] = "Refreshed the security state through the formal management channel.",
        ["Action.Security.PromoteSecureReady"] = "Promoted the secure-boot-ready hardened build as the preferred review target.",
        ["Action.Security.KeepDebugLimited"] = "Kept Debug HID explicitly limited to maintenance and lab workflows.",
        ["Action.Security.ApplyUpPersisted"] = "Wrote persisted user-presence config through the formal management channel.",
        ["Action.Security.ApplyUpSession"] = "Wrote session user-presence override through the formal management channel.",
        ["Action.Security.ClearUpSession"] = "Cleared the session user-presence override through the formal management channel.",
        ["Action.Maintenance.PrepareRelease"] = "Prepared the combined desktop preflight: Rust manager check plus WinUI manager build.",
        ["Action.Maintenance.ProbeReminder"] = "Added a reminder to route unknown boards through probe-board instead of ad-hoc debug steps.",
        ["Action.Activity.RecordSnapshot"] = "Refreshed the device information from the formal management channel.",
        ["Action.Activity.PinLinux"] = "Logged the current app and device version details.",
        ["Dialog.Close"] = "Close"
    };
}
